(()=>{'use strict';
const API='https://ekodi.kr/api/realtime',core=()=>window.EKODIChurchLive;
const $=id=>document.getElementById(id);const remote=new Map();
function auth(){const t=core()?.token?.()||'';return t?{authorization:`Bearer ${t}`}:{}}
async function req(path,opt={}){const r=await fetch(API+path,{...opt,headers:{accept:'application/json',...(opt.body?{'content-type':'application/json'}:{}),...auth(),...(opt.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function room(){return core()?.getState?.().room}
async function invite(){const r=room();if(!r)return core()?.note?.('방송방 생성 후 모바일 카메라를 초대할 수 있습니다.');const d=await req(`/rooms/${encodeURIComponent(r.id)}/camera-sources/invites`,{method:'POST',body:JSON.stringify({label:'모바일 카메라',expiresMinutes:10})});$('cameraInviteResult').innerHTML=`<label>10분 유효 초대 링크<input id="mobileCameraInviteLink" readonly value="${d.invite.joinUrl.replaceAll('&','&amp;').replaceAll('"','&quot;')}"></label><button type="button" id="copyMobileCameraInvite">링크 복사</button>`;$('copyMobileCameraInvite')?.addEventListener('click',()=>navigator.clipboard?.writeText(d.invite.joinUrl));}
async function mediaFor(source){const r=room();if(!r)return null;const detail=await req(`/rooms/${encodeURIComponent(r.id)}`);const tracks=(detail.tracks||[]).filter(t=>String(t.track_name||t.trackName||'').startsWith(`camera-source-${source.id}-`));if(!tracks.length)return null;const session=await req(`/rooms/${r.id}/sessions`,{method:'POST',body:JSON.stringify({role:'viewer'})});const pc=new RTCPeerConnection({iceServers:session.iceServers||[]}),stream=new MediaStream();pc.ontrack=e=>(e.streams?.[0]?.getTracks?.()||[e.track]).forEach(t=>{if(!stream.getTracks().some(x=>x.id===t.id))stream.addTrack(t)});const h={'x-ekodi-session-key':session.session.accessKey};const pulled=await req(`/rooms/${r.id}/sessions/${session.session.id}/pull`,{method:'POST',headers:h,body:JSON.stringify({tracks:tracks.map(t=>({trackName:t.track_name||t.trackName}))})});const offer=pulled?.provider?.sessionDescription||pulled?.provider?.data?.sessionDescription||pulled?.sessionDescription;if(!offer?.sdp)return null;await pc.setRemoteDescription(offer);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);await req(`/rooms/${r.id}/sessions/${session.session.id}/renegotiate`,{method:'PUT',headers:h,body:JSON.stringify({sessionDescription:pc.localDescription})});remote.set(source.id,{pc,stream});return stream}
function choose(stream,mode){const main=$('mainVideo'),screen=$('programScreen');if(!main||!stream)return;main.srcObject=stream;screen.dataset.sourceLayout=mode;if(mode==='pip'||mode==='split'){let extra=screen.querySelector('.mobile-source-preview');if(!extra){extra=document.createElement('video');extra.className='mobile-source-preview';extra.autoplay=true;extra.playsInline=true;screen.append(extra)}extra.srcObject=core()?.getState?.().local||stream;}else screen.querySelector('.mobile-source-preview')?.remove();}
async function connect(source,mode){let stream=remote.get(source.id)?.stream||await mediaFor(source);if(!stream)return core()?.note?.('모바일 영상 트랙 연결을 기다리는 중입니다.');choose(stream,mode);}
async function action(id,act){const r=room();await req(`/rooms/${r.id}/camera-sources/${id}/${act}`,{method:'POST',body:'{}'});await refresh();}
async function refresh(){const r=room();if(!r)return;const d=await req(`/rooms/${r.id}/camera-sources`);const box=$('cameraSourceList');box.innerHTML='';for(const s of d.sources||[]){const row=document.createElement('div');row.className='camera-source-row';row.innerHTML=`<strong>${s.label||'모바일 카메라'}</strong><small>${s.status}</small>`;if(s.status==='pending'){for(const a of [['approve','승인'],['revoke','거부']]){const b=document.createElement('button');b.textContent=a[1];b.onclick=()=>action(s.id,a[0]);row.append(b)}}else if(['approved','connected'].includes(s.status)){for(const a of [['main','메인'],['pip','PIP'],['split','분할']]){const b=document.createElement('button');b.textContent=a[1];b.onclick=()=>connect(s,a[0]);row.append(b)}const x=document.createElement('button');x.textContent='연결 해제';x.onclick=()=>action(s.id,'revoke');row.append(x)}box.append(row)}}
$('cameraInviteButton')?.addEventListener('click',()=>invite().catch(e=>core()?.note?.(`카메라 초대 실패: ${e.message}`)));$('cameraRefreshButton')?.addEventListener('click',()=>refresh().catch(()=>{}));setInterval(()=>refresh().catch(()=>{}),4000);
})();